-- 017: track -> country mapping for flag display on tsura.org.
-- Seeded by name research (2026-07-13); 'xx' = unknown/fictional (globe icon).
-- Admins maintain new tracks via the website's /admin/tracks page.
BEGIN;

CREATE TABLE IF NOT EXISTS webadmin.track_countries (
    track_name   text PRIMARY KEY,
    country_code text NOT NULL DEFAULT 'xx'
                 CHECK (country_code ~ '^[a-z]{2}(-[a-z]{2,3})?$'),
    updated_by   bigint,
    updated_at   timestamptz NOT NULL DEFAULT now()
);

GRANT USAGE ON SCHEMA webadmin TO tsura;
GRANT SELECT, INSERT, UPDATE, DELETE ON webadmin.track_countries TO tsura;

-- the /admin/tracks page lists ALL known tracks (also ones no mart view
-- shows yet); tsura may read exactly this one base table
GRANT USAGE ON SCHEMA base TO tsura;
GRANT SELECT ON base.tracks TO tsura;

INSERT INTO webadmin.track_countries (track_name, country_code) VALUES
    ('Abu Dhabi GP v1.03', 'ae'),
    ('Australian GP v1.15', 'au'),
    ('Australian GP v1.16', 'au'),
    ('Autodromo Do Estoril v1.02', 'pt'),
    ('Automotodrom Grobnik (F3)', 'hr'),
    ('Automotodrom Grobnik (McSimCad)', 'hr'),
    ('Automotodrom Zaluzani v0.1 Q', 'ba'),
    ('Automotodrom Zaluzani v0.1 R', 'ba'),
    ('Automotodrom Zaluzani v0.2 Q', 'ba'),
    ('Automotodrom Zaluzani v0.2 R', 'ba'),
    ('Automotodrom Zaluzani v1 Q', 'ba'),
    ('Automotodrom Zaluzani v1 R', 'ba'),
    ('Autovía del Vino', 'es'),
    ('Ayertown GP', 'xx'),
    ('Baku City Circuit v1.10', 'az'),
    ('Baku GP v1.00', 'az'),
    ('Baku GP v1.01', 'az'),
    ('Balaton Park Circuit v1.01', 'hu'),
    ('Bangowitch Circuit 1.02 (F3O)', 'xx'),
    ('Barcelona GP - 2023 Layout V1.1', 'es'),
    ('Barcelona GP - Catalunya v1.06', 'es'),
    ('Barcelona GP - Catalunya v1.1', 'es'),
    ('Bathurst Mount Panorama GrT V2.2', 'au'),
    ('Beerlowtown halloween v1.02', 'xx'),
    ('Bienvenidos a Las Parras', 'es'),
    ('Bikernieki (HSR) v1.0 Q', 'lv'),
    ('Bikernieki (HSR) v1.0 R', 'lv'),
    ('Bilster Berg v1.01', 'de'),
    ('Biķernieki (HSR) v0.87 Q', 'lv'),
    ('Biķernieki (HSR) v0.87 R', 'lv'),
    ('Bombtrack', 'xx'),
    ('Bowman Gray Death Battle', 'us'),
    ('Bowman Gray Stadium v2 (OSCR 26)', 'us'),
    ('Brands Hatch GP Circuit V2.01', 'gb'),
    ('Brands Hatch Indy Circuit V2.01', 'gb'),
    ('Brazilian GP v1.0', 'br'),
    ('Brazilian GP v1.01', 'br'),
    ('Brazilian GP v1.03 (Wet Look)', 'br'),
    ('Brazilian GP v1.03 (Wet Phys)', 'br'),
    ('Brazilian GP v1.04', 'br'),
    ('Brazilian GP v1.04 (Wet Look)', 'br'),
    ('Brazilian GP v1.04.2 (Wet Look)', 'br'),
    ('Brazilian GP v1.06 (Wet Look)', 'br'),
    ('Bristol (Road Course) v1.2', 'us'),
    ('Bristol Motor Speedway v1.0', 'us'),
    ('Broadbean Raceway V1.0', 'xx'),
    ('Buddh International Circuit v1.0', 'in'),
    ('Buenos Aires Eprix Circuit V1.01', 'ar'),
    ('Buffalo Hill - Rallycross v1.0', 'xx'),
    ('Buriram Intl. Circuit V1.00', 'th'),
    ('CSup - Lost Lagoons v1', 'xx'),
    ('Cadwell Park (Woodlands) WET', 'gb'),
    ('Cadwell Park (Woodlands) qualy', 'gb'),
    ('Cadwell Park (Woodlands) race', 'gb'),
    ('Cadwell Park (Woodlands) v0.1', 'gb'),
    ('Cadwell Park (Woodlands) v1.1', 'gb'),
    ('Camino del Estraperlo', 'es'),
    ('Canadian GP v1.12', 'ca'),
    ('Canadian GP v1.23', 'ca'),
    ('Candyville Sfinx v1.3', 'xx'),
    ('Castle Combe Circuit V1.00', 'gb'),
    ('Charlotte Speedway RC A V1.02', 'us'),
    ('Circuit Zandvoort V1.01', 'nl'),
    ('Circuit Zandvoort V1.03', 'nl'),
    ('Circuit Zandvoort V1.04', 'nl'),
    ('Circuit Zolder v1.03', 'be'),
    ('Circuit de Reims Gueux V1.01', 'fr'),
    ('Circuit of the Americas v1.031', 'us'),
    ('Circuit of the Americas v1.043', 'us'),
    ('Circuito Vasco Sameiro v1.1 Xmas', 'pt'),
    ('City heights', 'xx'),
    ('Daytona Intl. Road Course V3.00', 'us'),
    ('Daytona Intl. Speedway V3.00', 'us'),
    ('Daytona Road Course V2.01', 'us'),
    ('De Sluis v1.1', 'nl'),
    ('Detroit Street Circuit ICS V1.01', 'us'),
    ('Donington Park ''38 V1.0', 'gb'),
    ('Donnington Park (Prewar) v2', 'gb'),
    ('Elethasia Island Circuit v1.01', 'xx'),
    ('Firestone GP St.Petersburg v1.01', 'us'),
    ('Firston', 'xx'),
    ('Giza International Circuit V1.00', 'eg'),
    ('Gran Circo Ambulante', 'es'),
    ('Grizzlemaw Glacier 1.1', 'xx'),
    ('Hamburg EPrix Circuit V1.01', 'de'),
    ('Hassain Sula GP v1.00', 'xx'),
    ('Hockenheimring GP v1.41', 'de'),
    ('Hockenheimring GP v1.42', 'de'),
    ('Hong Kong Street Circuit V1.00', 'hk'),
    ('Hungaroring V2.04', 'hu'),
    ('Il Giro (full) v5.0', 'it'),
    ('Il Giro (short) v5.0', 'it'),
    ('Imola GP v1.16', 'it'),
    ('Indianapolis Nascar Oval v.1', 'us'),
    ('Indianapolis Speedway V1.00', 'us'),
    ('Japanese GP v2.01', 'jp'),
    ('Japanese GP v2.03', 'jp'),
    ('Japanese GP v2.13', 'jp'),
    ('Jäädytetty Indeksi - Club Layout', 'fi'),
    ('Kartland 2.0', 'xx'),
    ('Knockhill Racing Circuit Q (TraN', 'gb'),
    ('Knockhill Racing Circuit R (TraN', 'gb'),
    ('Knockhill Racing Circuit V2.00', 'gb'),
    ('Laguna Seca Raceway v1.02', 'us'),
    ('Laguna Seca Raceway v1.5', 'us'),
    ('Lakeside GP v2.0', 'au'),
    ('Las Parras Street Endurance Ring', 'es'),
    ('Lausitzring - GP Layout v1.1', 'de'),
    ('Lausitzring - Tri-Oval v1.2', 'de'),
    ('Lime Rock Park GP V2.00', 'us'),
    ('Lime Rock Park V2.00', 'us'),
    ('Lime Rock Park V2.00 (Q)', 'us'),
    ('Lime Rock Park V2.00 (QW)', 'us'),
    ('Lime Rock Park V2.00 (R)', 'us'),
    ('Lime Rock Park V2.00 (RW)', 'us'),
    ('Long Beach Circuit ICS v1', 'us'),
    ('Long Beach Circuit v1.1', 'us'),
    ('Lotta Sisu Circuit v1.2', 'fi'),
    ('Lusail Intl. Circuit V3.02', 'qa'),
    ('Magic Mushroom Forest', 'xx'),
    ('Martinsville v2.4.1', 'us'),
    ('Mexico City Eprix 2026 V1.00', 'mx'),
    ('Miami GP v1.02', 'us'),
    ('Milwaukee Mile (OSCR)', 'us'),
    ('Milwaukee Mile Road Course V1.00', 'us'),
    ('Milwaukee Mile V1.00', 'us'),
    ('Misano World Circuit V2.00', 'it'),
    ('Monaco GP v1.03', 'mc'),
    ('Motorsport Arena Oschersleben v1', 'de'),
    ('Motorsport Arena Oschersleben v2', 'de'),
    ('Mountains of Madness', 'xx'),
    ('NHMS v1 (OSCR 26)', 'us'),
    ('NHMS v1 (OSCR ASR 26)', 'us'),
    ('NHMS v1 (OSCR ASR 26) Q', 'us'),
    ('Nanoli Full Circuit v1.4', 'xx'),
    ('Nashville Music City GP v1.02', 'us'),
    ('Nashville SuperSpeedway V1.00ICS', 'us'),
    ('National Racetrack Monza v1.5', 'it'),
    ('New Hampshire Motor Speedway v1', 'us'),
    ('Nordschleife.zip', 'de'),
    ('Nordschleife.zip v1.1', 'de'),
    ('Nordschleife.zip v1.5', 'de'),
    ('Norisring v1.03', 'de'),
    ('Nurburgring GP Circuit v1.2', 'de'),
    ('Off The Road', 'xx'),
    ('Owl Forest Hills', 'xx'),
    ('Parasite Coast Run v1.00', 'xx'),
    ('Paska Kaupunni', 'fi'),
    ('Philip Island V8SC V1.0', 'au'),
    ('Phoenix Raceway v1', 'us'),
    ('Portland Int. Raceway ICS V1.01', 'us'),
    ('Puente del Pisado', 'es'),
    ('Punta del Este Eprix V1.00', 'uy'),
    ('Quarry', 'xx'),
    ('Queensland Raceway V1.00', 'au'),
    ('RC Playground Zero v3', 'xx'),
    ('Raijin Mountain Circuit v1.00nsd', 'jp'),
    ('RedBull Ring GP v1.40', 'at'),
    ('Road America V2.0', 'us'),
    ('Road America V2.02', 'us'),
    ('Road America V2.02 ICS', 'us'),
    ('Road Atlanta (no extra roads)', 'us'),
    ('Road Atlanta (this one)', 'us'),
    ('Road Atlanta v0.9 Q', 'us'),
    ('Road Atlanta v0.9 R', 'us'),
    ('Rosenholm Circuit', 'xx'),
    ('Rushgrove', 'xx'),
    ('SSS. Aeropuerto de Las Parras', 'es'),
    ('Sachsenring GP Circuit v1.2', 'de'),
    ('Sebring v0.9912', 'us'),
    ('Sebring v0.9975', 'us'),
    ('Sebring v0.9993 Q', 'us'),
    ('Sebring v0.9993 R', 'us'),
    ('Sebring v1.0 MX-5 Edition', 'us'),
    ('Sepang Circuit V2.01', 'my'),
    ('Sepang Circuit V2.02', 'my'),
    ('Shanghai Circuit V2.01', 'cn'),
    ('Silverstone Circuit V1.04', 'gb'),
    ('Silverstone Circuit V1.05', 'gb'),
    ('Silverstone Circuit V1.07', 'gb'),
    ('Singapore Street Circuit v1.1', 'sg'),
    ('Sliders Island v1.0', 'xx'),
    ('Snetterton V1.2', 'gb'),
    ('Spa Francorchamps GP v3.11', 'be'),
    ('Spa Francorchamps GP v3.12', 'be'),
    ('Spa Francorchamps GP v3.21', 'be'),
    ('Spa Francorchamps GP v3.22', 'be'),
    ('Surfers Paradise', 'au'),
    ('Suzuka (East Circuit) v1 Q', 'jp'),
    ('Suzuka (East Circuit) v1 QW', 'jp'),
    ('Suzuka (East Circuit) v1 R', 'jp'),
    ('Suzuka (East Circuit) v1 RW', 'jp'),
    ('TT Circuit Assen V1.7', 'nl'),
    ('Talladega Superspeedway v1.2', 'us'),
    ('Talladega Superspeedway v1.2.1', 'us'),
    ('Taupo Motorsport Park T1 v1.0.0', 'nz'),
    ('Testing Sebring v1.2', 'us'),
    ('Thunder Point', 'xx'),
    ('Tilksport GP v2', 'xx'),
    ('Tomula GP v2.01', 'fi'),
    ('Trial Mountain Circuit v2.02', 'xx'),
    ('Tsukuba Circuit', 'jp'),
    ('TurboCross(TM) v1.0', 'xx'),
    ('UlpettilaSörkit v11', 'fi'),
    ('VSR-Homeland V1.5', 'xx'),
    ('Vinolinera', 'es'),
    ('Watkins Glen Int. Short (NASCAR)', 'us'),
    ('Watkins Glen International v1.3', 'us'),
    ('Watkins Glen International v1.5', 'us'),
    ('Watkins Glen Short v1.03', 'us'),
    ('Watkins Glen Short v1.05', 'us'),
    ('Xerkox v6', 'xx'),
    ('Yas Marina 2021 GP v1.4.2', 'ae'),
    ('Yksinäisille Vuorille', 'fi')
ON CONFLICT (track_name) DO NOTHING;

COMMIT;
